### PR TITLE
Simplify redirects of legacy docs

### PR DESCRIPTION
**Pull request by driehle**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

The docs folder contains several manual redirects, i.d. HTML documents with a hard-coded redirect for legacy URLs. With the [adoption of the MkDocs redirect plugin](https://github.com/laminas/documentation-theme/pull/65) there is a simpler solution available.

This PR moves the redirects for legacy URLs in `mkdocs.yml` and removes the manually created HTML documents from Git.

### CODE REVIEW

**Comment by driehle** [comment]
Markdownlint issues addressed according to froschdesign's comment in https://github.com/laminas/laminas-di/pull/33#issuecomment-942021317

**Comment by Ocramius** [comment]
I've re-targeted this for the next minor: could you please rebase?

**Comment by driehle** [comment]
Rebased on `3.6.x`

**Review by Ocramius — APPROVED** [review]
Thanks! :muscle:

**Pull request merged**
